# Generated by Django 5.0.7 on 2024-07-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.CharField(blank=True, max_length=300)),
                ('role', models.CharField(choices=[('D', 'Driver'), ('C', 'Customer')], help_text='Please register as Driver or Customer', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
