# Generated by Django 5.0.7 on 2024-07-30 10:28

from django.db import (
    migrations,
    models,
)


class Migration(
    migrations.Migration
):
    dependencies = [
        (
            "users",
            "0002_passenger_delete_testclass_remove_user_role",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="credit_card",
            field=models.CharField(
                blank=True
            ),
        ),
    ]
