# Generated by Django 5.0.7 on 2024-09-18 13:16

from django.db import (
    migrations,
)


class Migration(
    migrations.Migration
):
    dependencies = [
        (
            "users",
            "0006_driver_rides_offered_passenger_rides_taken",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="rating",
        ),
    ]
