# Generated by Django 5.0.7 on 2024-07-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        ('users', '0006_customer_driver_delete_loginuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_location', models.CharField()),
                ('destination', models.CharField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferRide',
            fields=[
                ('riderequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rides.riderequest')),
                ('arrival_time', models.IntegerField()),
                ('price', models.FloatField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
            ],
            bases=('rides.riderequest',),
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
        migrations.CreateModel(
            name='AcceptedRide',
            fields=[
                ('offerride_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rides.offerride')),
                ('accepted_on', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('rides.offerride',),
        ),
    ]
