# Generated by Django 5.0.7 on 2024-08-01 08:21

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(
    migrations.Migration
):
    dependencies = [
        (
            "rides",
            "0001_initial",
        ),
        (
            "users",
            "0003_passenger_credit_card",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequest",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.passenger",
            ),
        ),
    ]
