# Generated by Django 5.0.7 on 2024-08-01 12:34

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(
    migrations.Migration
):
    dependencies = [
        (
            "rides",
            "0003_rideoffer",
        ),
        (
            "users",
            "0003_passenger_credit_card",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="rideoffer",
            old_name="ride",
            new_name="ride_request",
        ),
        migrations.CreateModel(
            name="RideAccepted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accepted_on",
                    models.DateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rides.rideoffer",
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.passenger",
                    ),
                ),
            ],
        ),
    ]
