# Generated by Django 5.0.7 on 2024-08-29 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_rename_ride_rideoffer_ride_request_rideaccepted'),
        ('users', '0006_driver_rides_offered_passenger_rides_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideoffer',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='rideoffer',
            name='ride_request',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='passenger',
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_location', models.CharField()),
                ('destination', models.CharField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.passenger')),
            ],
        ),
        migrations.DeleteModel(
            name='RideAccepted',
        ),
        migrations.DeleteModel(
            name='RideOffer',
        ),
        migrations.DeleteModel(
            name='RideRequest',
        ),
    ]
