# Generated by Django 5.0.7 on 2024-09-19 13:43

from django.db import (
    migrations,
    models,
)


class Migration(
    migrations.Migration
):
    dependencies = [
        (
            "rides",
            "0006_ride_dropoff_time_ride_ride_duration_ride_ride_uuid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
    ]
