# Generated by Django 5.1.1 on 2024-09-21 14:09

from django.db import (
    migrations,
)


class Migration(
    migrations.Migration
):
    dependencies = [
        (
            "rides",
            "0007_alter_ride_end_time_alter_ride_start_time",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="passenger",
        ),
    ]
